---
kind: pipeline

steps:
  - name: build
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - echo Hello World

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
